DataDog/oracle-cloud-integration

Service Connector  Hub/README.md
Service Connector  Hub/func.py
Service Connector  Hub/func.yaml
Service Connector  Hub/tests/test_func.py

What does this PR do?
---------------------
Add support for batch CloudEvents which is a list.
Corrects memory setting in yaml.
Who will it impact?
-------------------
New users of OCI function to forward logs.
Motivation
----------
Issue reported via CLOUDS-1802
Testing Guidelines
------------------
Built the application on Oracle Cloud Shell.
Reproduced both errors and fixed through unit tests.
Release Checklist
-----------------
See Also: https://github.com/DataDog/devops/wiki/Code-Workflow#deploying-to-production
Security Checklist
-------------------
This PR creates, modifies, or deletes:
Unsure? Have a question? Request a review from `@DataDog/osa`!
Additional Notes
----------------

Add support for batch format of CloudEvents

---

datadog-oci-orm/metrics-setup/locals.tf
datadog-oci-orm/metrics-setup/serviceconnector.tf

* Add default namespaces when creating connector hub
* Currently limited to 50 total namespaces for a single connector hub

ECI-221 Add default namespaces when creating connector hub

---

Object Store/func.py
Service Connector  Hub/func.py

**what:**
* Change source constant to `oracle_cloud` in log forwarding function
* In service connector log forwarding function, change `ddsource` field value to `oracle_cloud`
**why:**
* The log forwarding takes the the `ddsource` value as `oracle_cloud` without that the logs are not accepted

ECI-161 Fix ddsource in log forwarding function

---

Service Connector  Hub/func.py
Service Connector  Hub/func.yaml
Service Connector  Hub/tests/test_func.py
Service Connector  Hub/tests/test_request.py

- Added DD_COMPRESS optional environment variable to specify if requests should be compressed or not. By default, they will be compressed
- Updated DATADOG_HOST variable to reflect environment, rather than the url
- Batching upto 1000 log events before calling Datadog API
- Modified test_request script to prepend message number, if producing more than 1 message, for easier testing
- Updated unit tests to account for above changes 
- DD_COMPRESS environment variable added to support benchmarking tests, with and without compression.
- Batching of events done to reduce number of API requests sent, hence reducing network traffic
- DD_HOST changes done to support expansion to multiple logs intake urls per datacenter, if needed
1. Set DD_COMPRESS environment variable to false. Produce 1 message …

[ECI-236] Batch logs

---

datadog-oci-orm/metrics-setup/schema.yaml

Removes `ddog-gov` from Datadog site dropdown. 
Datadog GovCloud is currently not supported for the OCI integration, so we are removing the option to forward metrics there.

Remove ddog-gov from site dropdown

---

Service Connector  Hub/requirements.txt

Fix the yaml package name. The correct name is pyyaml
- https://github.com/DataDog/oracle-cloud-integration/issues/16
- Ran pip install and tests, and works correctly

Fix package name

---

datadog-oci-orm/policy-setup/policy.tf
datadog-oci-orm/policy-setup/variables.tf

**what:**
* Update the terraform stack in OCI policy setup to create a user, user group and policy for the user to read resources in the tenancy
**why:**
* Step in the  the ease of setup of automated creation of policy and user
**testing:**
[Created stack job](https://cloud.oracle.com/resourcemanager/jobs/ocid1.ormjob.oc1.iad.amaaaaaaehwejaiaow7txjuiazzauzyhhxuecrei6tyhzwhvq65b2nk5pyya?region=us-ashburn-1)

ECI-258 Terraform stack update that adds an auth user, group and policy

---

datadog-oci-orm/metrics-setup/connector_namespaces.py
datadog-oci-orm/metrics-setup/data.tf
datadog-oci-orm/metrics-setup/function_setup.tf
datadog-oci-orm/metrics-setup/functions.tf
datadog-oci-orm/metrics-setup/locals.tf
datadog-oci-orm/metrics-setup/outputs.tf
datadog-oci-orm/metrics-setup/schema.yaml
datadog-oci-orm/metrics-setup/serviceconnector.tf
datadog-oci-orm/metrics-setup/variables.tf

**what:**
* Add additional settings for connector hub.
* While running the terraform stacks, provides additional options:
- Comma separated list of compartment ids
- List of namespaces to include. 
- The final list of namespaces in each compartment is an intersection of existing metrics namespaces in that compartment and the selected namespaces.
**why:**
* For better customer experience of adding additional compartments and not just root compartmen
**testing:**
The existing stack can be [seen here](https://cloud.oracle.com/resourcemanager/privateTemplateProviders/ocid1.ormtemplate.oc1.iad.amaaaaaaehwejaiazepd7rxtbgjxt6qh6qhlp37yomwvwgaqfdg6ctpx3btq?region=us-ashburn-1)

ECI-208 Add additional connector hub settings

---

datadog-logs-oci-orm/logs-function/func.py
datadog-logs-oci-orm/logs-function/tests/test_func.py

We need to forward the "oracle" and "type" attributes from OCI logs to get all the information for facets.
Also, we need to be able to distinguish what type of log we are sending from OCI to dd, so this PR checks if the log is a service log. If it is not, it extracts the service name from the "type" attribute.

ECI [OCI] include more log attributes and assign "DD_SOURCE" based on OCI service

---

datadog-logs-oci-orm/locals.tf
datadog-logs-oci-orm/main.tf
datadog-logs-oci-orm/modules/containerregistry/data.tf
datadog-logs-oci-orm/modules/containerregistry/locals.tf
datadog-logs-oci-orm/modules/containerregistry/login.tf
datadog-logs-oci-orm/modules/containerregistry/variables.tf
datadog-logs-oci-orm/modules/functionapp/main.tf
datadog-logs-oci-orm/modules/functionapp/variables.tf
datadog-logs-oci-orm/modules/policy/locals.tf
datadog-logs-oci-orm/modules/policy/main.tf
datadog-logs-oci-orm/modules/policy/variables.tf
datadog-logs-oci-orm/outputs.tf
datadog-logs-oci-orm/schema.yaml
datadog-logs-oci-orm/variables.tf

- Replace exclude_services with include_services
- Replace CSV Upload for compartments with Comma separated values for compartments to align with the current metrics experience
- Update Docker inputs to align with the current metrics experience
- Remove Function Shape variable to align with current metrics experience
- Prepare for Private Beta Launch for Logs
- Stack : [Link](https://cloud.oracle.com/resourcemanager/stacks/ocid1.ormstack.oc1.iad.amaaaaaaehwejaiauihole7chllbzqygt3t2b7tt2heh7drsvimkeulzc7bq?region=us-ashburn-1)

Sva91/ECI-399 E2E logs private beta update stack

---

datadog-logs-oci-orm/locals.tf
datadog-logs-oci-orm/main.tf
datadog-logs-oci-orm/modules/connectorhub/locals.tf
datadog-logs-oci-orm/modules/connectorhub/main.tf
datadog-logs-oci-orm/modules/connectorhub/output.tf
datadog-logs-oci-orm/modules/connectorhub/variables.tf
datadog-logs-oci-orm/modules/containerregistry/data.tf
datadog-logs-oci-orm/modules/containerregistry/locals.tf
datadog-logs-oci-orm/modules/containerregistry/login.tf
datadog-logs-oci-orm/modules/containerregistry/variables.tf
datadog-logs-oci-orm/modules/functionapp/main.tf
datadog-logs-oci-orm/modules/functionapp/variables.tf
datadog-logs-oci-orm/modules/logging/data.tf
datadog-logs-oci-orm/modules/logging/output.tf
datadog-logs-oci-orm/modules/logging/search_logs_outside_compartment.sh
datadog-logs-oci-orm/modules/logging/variables.tf
datadog-logs-oci-orm/modules/policy/locals.tf
datadog-logs-oci-orm/modules/policy/main.tf
datadog-logs-oci-orm/modules/policy/variables.tf
datadog-logs-oci-orm/outputs.tf
datadog-logs-oci-orm/schema.yaml
datadog-logs-oci-orm/variables.tf

- Creates 1 Connector hub for service logs. This connector hub forwards logs from log groups generated to collect service logs
- Creates 1 connector hub for audit logs. This connector hub forward logs from compartments if "Enable Audit Log Forwarding" is selected
- Set up Infrastructure for Log Forwarding
- Logs in DD : [Link](https://app.datadoghq.com/logs?query=source%3Aoci.%2A&agg_m=count&agg_m_source=base&agg_q=status%2Cservice%2Csource&agg_q_source=base%2Cbase%2Cbase&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice%2Csource&fromUser=true&messageDisplay=inline&refresh_mode=paused&sort_m=%2C%2C&sort_m_source=%2C%2C&sort_t=%2C%2C&storage=hot&stream_sort=desc&top_n=10%2C10%2C10&top_o=top%2Ctop%2Ctop&viz=stream&x_missing=true%2Ctrue%2Ctrue&from_ts=1738608423516&to_ts=1 …

ECI-398 Add connectorhub module

---

datadog-logs-oci-orm/data.tf
datadog-logs-oci-orm/locals.tf
datadog-logs-oci-orm/main.tf
datadog-logs-oci-orm/modules/connectorhub/locals.tf
datadog-logs-oci-orm/modules/connectorhub/main.tf
datadog-logs-oci-orm/modules/connectorhub/output.tf
datadog-logs-oci-orm/modules/connectorhub/variables.tf
datadog-logs-oci-orm/modules/containerregistry/data.tf
datadog-logs-oci-orm/modules/containerregistry/locals.tf
datadog-logs-oci-orm/modules/containerregistry/login.tf
datadog-logs-oci-orm/modules/containerregistry/variables.tf
datadog-logs-oci-orm/modules/functionapp/main.tf
datadog-logs-oci-orm/modules/functionapp/variables.tf
datadog-logs-oci-orm/modules/logging/data.tf
datadog-logs-oci-orm/modules/logging/locals.tf
datadog-logs-oci-orm/modules/logging/main.tf
datadog-logs-oci-orm/modules/logging/output.tf
datadog-logs-oci-orm/modules/logging/search_logs_outside_compartment.sh
datadog-logs-oci-orm/modules/logging/variables.tf
datadog-logs-oci-orm/modules/policy/locals.tf
datadog-logs-oci-orm/modules/policy/main.tf
datadog-logs-oci-orm/modules/policy/variables.tf
datadog-logs-oci-orm/modules/resourcediscovery/search_resources.sh
datadog-logs-oci-orm/outputs.tf
datadog-logs-oci-orm/schema.yaml
datadog-logs-oci-orm/variables.tf

- Get All log groups in tenancy, and get all logs from log groups. This is required because log resources for resources from which we want to forward logs maybe present in other compartments.
- Add timeCreated field for resources in discovery. This helps add deterministic behavior for log creation
- Add logging module
1. It takes in resources from which logs should be forwarded for a compartment, all existing log resources in tenancy and services from which logs need to be forwarded.
2. It finds existing loggroups from which logs should be forwarded.
3. It creates a new log group "datadog-service-logs" in the compartment.
4. It generates log resources for resources which don't have logging already enabled.
5. It outputs existing loggroups and loggroup id for the newly created …

[ECI-396] Add logging module

---

datadog-oci-orm/metrics-setup/functions.tf
datadog-oci-orm/metrics-setup/schema.yaml
datadog-oci-orm/metrics-setup/variables.tf

**what:**
Allow customers to specify image shape in metric stack
**why:**
Customers in Japan regions cannot use GENERIC_ARM shape
**testing:**
Ran stack successfully

ECI [OCI] add back option to change image shape for metrics

---

datadog-oci-orm/metrics-setup/function_setup.tf
datadog-oci-orm/metrics-setup/locals.tf

**what:**
* Create docker registry login for ocir regions in a different way
**why:**
* For the docker login in a commercial region, the format used is: `<region-code>.ocir.io`
* The gov regions use canonical endpoints because ocir.io is not supported there.
* The URL in gov region should be: `ocir.$region_name.oci.oraclegovloud.com`

ECI-446 Handle OCIR repo URL for gov cloud

---

datadog-oci-orm/metrics-setup/auth_token.py
datadog-oci-orm/metrics-setup/data.tf
datadog-oci-orm/metrics-setup/function_setup.tf
datadog-oci-orm/metrics-setup/functions.tf
datadog-oci-orm/metrics-setup/locals.tf
datadog-oci-orm/metrics-setup/outputs.tf
datadog-oci-orm/metrics-setup/schema.yaml
datadog-oci-orm/metrics-setup/serviceconnector.tf
datadog-oci-orm/metrics-setup/variables.tf
datadog-oci-orm/metrics-setup/vcn.tf
datadog-oci-orm/policy-setup/policy.tf
datadog-oci-orm/policy-setup/variables.tf

**what:**
** Policy changes:**
* Create a new user `DatadogAuthWriteUser` which is  used in pushing docker images.
* Change the name of the groups, dynamic group, policy and users so that it doesn't collide with existing stack.
* Remove the option for the name of group name, policy and dynamic group name
**Metric stack:**
* The docker images are only created with the user login created through policy stack.
* If the user is not created through policy stack then no resource will be created.
* A new auth token is created every time on stack run so it is not required to store the credential. It takes at least 60-120 sec for the token to be accepted and used for docker login.
**why:**
* To reduce additional complexity in docker credentials.
**testing:**
* Tested on `datadog84` tenancy. See …

ECI-455 Add service account user for metrics setup and docker images

---

datadog-oci-orm/metrics-setup/function_setup.tf
datadog-oci-orm/metrics-setup/functions.tf
datadog-oci-orm/metrics-setup/locals.tf
datadog-oci-orm/policy-setup/policy.tf
datadog-oci-orm/policy-setup/variables.tf

**what:**
* The docker login re-creates a service user auth token and does a login which takes at least 2-3 minutes.
* This can be skipped if not creating a function image and only refreshing connector hub compartments.

ECI-529 Do not do docker login on every stack run

---

datadog-functions/docker-images.sh

**what:**
* Automatic script to push docker images to the OCI container repository in the tenancy
* Takes the following inputs:
* login user, password, tenancy namespace and image tag
* Builds metrics and log forwarder images
* In addition to the tag, also pushes the same image with `latest` tag.
**why:**
**testing:**
* Tested in `datadog84` tenancy and was able to successfully push images in all subscribed regions

ECI-639 Add automated pushing of images to docker registry

---

datadog-integration/modules/auth/main.tf

Accidentally removed the block which associates private key with the user. Reverting that part.

revert additional delete

---

datadog-integration/data.tf
datadog-integration/locals.tf
datadog-integration/main.tf
datadog-integration/modules/key/data.tf
datadog-integration/modules/key/locals.tf
datadog-integration/modules/key/main.tf
datadog-integration/modules/key/outputs.tf
datadog-integration/modules/regional-stacks/data.tf
datadog-integration/modules/regional-stacks/locals.tf
datadog-integration/modules/regional-stacks/main.tf
datadog-integration/regional_stack.tf

**what:**
* Find the image sha of the metrics and logs image with `latest` tag and use it as image digest paramter in the function.
* This ensures that re-running the stack will apply the latest digest to the function in case the image is updated.
* Some terraform formatting of existing files. No actual changes. All necessary changes in: `datadog-integration/modules/regional-stacks/`

ECI-640 Add image sha to OCI functions

---

datadog-integration/data.tf
datadog-integration/locals.tf
datadog-integration/main.tf
datadog-integration/modules/auth/data.tf
datadog-integration/modules/auth/locals.tf
datadog-integration/modules/auth/main.tf
datadog-integration/modules/auth/outputs.tf
datadog-integration/modules/auth/variables.tf
datadog-integration/modules/compartment/locals.tf
datadog-integration/modules/compartment/main.tf
datadog-integration/modules/compartment/outputs.tf
datadog-integration/modules/compartment/variables.tf
datadog-integration/modules/integration/main.tf
datadog-integration/modules/key/data.tf
datadog-integration/modules/key/locals.tf
datadog-integration/modules/key/main.tf
datadog-integration/modules/key/variables.tf
datadog-integration/modules/kms/main.tf
datadog-integration/modules/regional-stacks/data.tf
datadog-integration/modules/regional-stacks/locals.tf
datadog-integration/modules/regional-stacks/main.tf
datadog-integration/modules/regional-stacks/outputs.tf
datadog-integration/modules/regional-stacks/variables.tf
datadog-integration/pre_check.py
datadog-integration/providers.tf
datadog-integration/regional_stack.tf
datadog-integration/schema.yaml
datadog-integration/variables.tf

ECI-650, ECI-684, ECI-649: changes to allow "advanced" parameters as inputs.
This is meant to be run from OCI RM Stack.
1. Non default domain usage: the domain is the currently logged in domain. Default is no longer assumed.
2. Choice of subnet for forwarding functions: allow input of a list of subnet OCIDs, one per region. The final set of regional stacks is an intersection of (tenancy subscribed regions, domain replicated regions, input subnet regions]. This input is optional. If left empty (default), the stack creates a VCN with subnets in all subscribed regions.
3. Choice of Compartment for deploying stack resources. If left empty, we will create/use the "Datadog" compartment.
4. Choice of Group/User. If left empty (default), we create a User and Group. Otherwise, we use the supplied …

ECI-684: add support for identity domains and advanced inputs

---

datadog-integration/delete_stack.sh
datadog-integration/modules/key/main.tf
datadog-integration/regional_stack.tf

- If we run OCI CLI commands, suppress warnings to ensure json doesn't get corrupted
- Add detailed logging in key module
- Debugging API Key generation related issues
- Deployed the [stack](https://cloud.oracle.com/resourcemanager/stacks/ocid1.ormstack.oc1.sa-vinhedo-1.amaaaaaai76osliaw4ebbudgncq7kamhhcd3moic3gsajd6rlkmbci4e3kna?region=sa-vinhedo-1).

Add more logging to key module

---

datadog-integration/regional_stack.tf

- Wait for Stack to become Active before kicking off a job
- Defensively retry job creation 5 times if they fail.
- Job Creation Failure won't fail the stack
- Resiliency to stack apply
- [Stack](https://cloud.oracle.com/resourcemanager/stacks/ocid1.ormstack.oc1.sa-vinhedo-1.amaaaaaai76osliat6i2y5v7p2sf5iu2s7mdkxtign6jjr7h7uh6rg3j3xaq?region=sa-vinhedo-1)

Retry Regional Stack Job Creation

---

datadog-integration/modules/key/main.tf

- Query one user instead of looking over all users of a domain
- Performance improvement
- [Stack](https://cloud.oracle.com/resourcemanager/stacks/ocid1.ormstack.oc1.sa-vinhedo-1.amaaaaaai76osliaz5awyngwleapg32p7rh2ad4hwhtbwbyrn43jgxruhoqq?region=sa-vinhedo-1)

optimize user id lookup

---

datadog-integration/data.tf

**What:**
Add filter for Active identity domains only
**Why:** 
Would receive 403 error when stack was unable to search users in inactive identity domain
**How was it tested?:**
replicated and fixed on staging

Add filter for active identity domains
